BusReservation.WebUI/Controllers/BusReservationController.cs
using BusReservation.Business.Abstract;
using BusReservation.Entity;
using BusReservation.WebUI.EmailServices;
using BusReservation.WebUI.Models;

using Microsoft.AspNetCore.Mvc;

using Newtonsoft.Json;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace BusReservation.WebUI.Controllers
{
    public class BusReservationController : Controller
    {
        private IRouteService _routeService;
        private ITicketService _ticketService;
        private IEmailSender _emailSender;

        public BusReservationController(IRouteService routeService, ITicketService ticketService, IEmailSender emailSender)
        {
            _routeService = routeService;
            _ticketService = ticketService;
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return View(); 
        } 

        public IActionResult FindRoute(string cityFirst, string cityLast, DateTime goingDate)
        {
            if (cityFirst == cityLast)
            {
                ShowMessage("Başlangıç ve Bitiş Rotaları Aynı Olamaz", "danger");
                return Redirect("~/");

            }
            ViewBag.From = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(cityFirst);
            ViewBag.ToWhere = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(cityLast);
            return View(_routeService.FindRoute(cityFirst,cityLast,goingDate));
        }
        public IActionResult GetTicketsFromRoute(int id, string cityFirst, string cityLast)
        {
            ViewBag.From = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(cityFirst);
            ViewBag.ToWhere = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(cityLast);
            int x = _routeService.GetRouteFromRouteId(id);
            ViewBag.x = x;
            return View(_ticketService.GetTicketsWithRoute(id));
        }
        public IActionResult GetPassangerInfo(string FromWhere, string ToWhere,int routeId, int seatNo)
        {
            Random rnd = new Random();
            int pnr = rnd.Next(100000000, 900000000);
            
            string routeHour = _ticketService.GetHour(routeId);
            string routeDate = _ticketService.GetDate(routeId);
            double routePrice = _ticketService.GetPrice(routeId);
            
            var ticket = new Ticket()
            {
                RouteId = routeId,
                TicketDate = routeDate,
                TicketPrice = routePrice,
                TicketClock = routeHour,
                TicketFromWhere = FromWhere,
                TicketSeatNo = seatNo,
                TicketPnrNo = pnr.ToString(),
                TicketToWhere = ToWhere
            };
            return View(ticket);
        }
        [HttpPost]
        public async Task<IActionResult> CreateTicket(Ticket ticket)
        {
            string htmlMes = $"<h4>Sayın {ticket.TicketName} Rezervasyon Bilgileriniz Aşağıdadır.</h4>" +
                $"<h6>PNR No: = {ticket.TicketPnrNo}</h6>" +
                $"<h6>İsim = {ticket.TicketName}</h6>" +
                $"<h6>Soyisim = {ticket.TicketSurname}</h6>" +
                $"<h6>Nereden = {ticket.TicketFromWhere}</h6>" +
                $"<h6>Nereye = {ticket.TicketToWhere}</h6>" +
                $"<h6>Tarih = {ticket.TicketDate}</h6>" +
                $"<h6>Saat = {ticket.TicketClock}</h6>" +
                $"<h6>Koltuk No = {ticket.TicketSeatNo}</h6>";
            await _emailSender.SendEmailAsync(ticket.TicketMail, "Varlı Seyahat Rezervasyon Bilgileri", htmlMes);
            _ticketService.Create(ticket);
            return View(ticket);
        }
        private void ShowMessage(string message, string type)
        {
            var msg = new AlertMessage()
            {
                Message = message,
                Type = type
            };
            TempData["Message"] = JsonConvert.SerializeObject(msg);
        }
    }
}

BusReservation.WebUI/Controllers/HomeController.cs
using BusReservation.Business.Abstract;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BusReservation.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private ICityService _cityService;
        public HomeController(ICityService cityService)
        {
            _cityService = cityService;
        }

        public IActionResult Index()
        {
            return View(_cityService.GetAll());
        }

       
    }
}

BusReservation.WebUI/Controllers/TicketController.cs
using BusReservation.Business.Abstract;
using BusReservation.Entity;
using BusReservation.WebUI.EmailServices;
using BusReservation.WebUI.Models;

using Microsoft.AspNetCore.Mvc;

using Newtonsoft.Json;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BusReservation.WebUI.Controllers
{
    public class TicketController : Controller
    {
        private ITicketService _ticketService;

        public TicketController(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Search(string PnrNo, string Email)
        {
            if (PnrNo == null || Email == null)
            {
                ShowMessage("Lütfen bilgilerin hepsini doldurun.", "danger");
                return RedirectToAction("Index", "Home");
            }
            var ticket = _ticketService.GetSearchedTicket(PnrNo, Email);
            if (ticket == null)
            {
                ShowMessage("Böyle bir bilet bulunmamaktadır.Lütfen bilgilerinizi kontrol ediniz.", "danger");
                return RedirectToAction("Index", "Home");
            }
            return View(ticket); 
        }
        public IActionResult TicketDelete(int ticketId)
{
            var entity = _ticketService.GetById(ticketId);
            _ticketService.Delete(entity);
            return RedirectToAction("Index", "Home");
        }
        private void ShowMessage(string message, string type)
        {
            var msg = new AlertMessage()
            {
                Message = message,
                Type = type
            };
            TempData["Message"] = JsonConvert.SerializeObject(msg);
        }
    }
}

BusReservation.WebUI/Views/Home/Index.cshtml
@model List<City>
@*@{
    ViewData["Title"] = "Home Page";
}*@

<div class="home-select d-flex row">
    <div class="choose-route row">
        <form class="bg-white col-md-8 mt-2" asp-action="FindRoute" asp-controller="BusReservation" onsubmit="return checkForm(this);">
            <fieldset>
                <div class="row justify-content-around">
                    <div class="mb-3 col-md-6">
                        <label class="form-label">Nereden</label>
                        <select class="form-select" name="cityFirst">
                            @foreach (var item in Model)
                            {
                                <option class="form-control" name="cityFirst">@item.CityName</option>
                            }
                        </select>
                    </div>
                    <div class="mb-3 col-md-6">
                        <label class="form-label">Nereye</label>
                        <select class="form-select" name="cityLast">
                            @foreach (var item in Model)
                            {
                                <option class="form-control" name="cityLast">@item.CityName</option>
                            }
                        </select>

                    </div>
                    <div class="mb-3 col-md-6">
                        <label class="form-label" id="validationDate">Tarih</label>
                        <input type="date" class="form-control" name="goingDate" required pattern="\d{1,2}/\d{1,2}/\d{4}">
                    </div>
                    <div class="my-4 col-md-6">
                        <button type="submit" class="btn btn-primary align-self-end mt-2">Rota Ara</button>
                    </div>
                </div>
            </fieldset>
        </form>
        <div class="col-md-4">
            <form asp-action="Search" asp-controller="Ticket" class="my-3">
                <div class="card text-center">
                    <div class="card-header ">
                        Rezervasyon İptal
                    </div>
                    <div class="card-body">
                        <input type="text" name="PnrNo" class="form-control my-3" placeholder="PNR Numarası Giriniz." />
                        <input type="text" name="Email" class="form-control mb-3" placeholder="Email Adresinizi Giriniz." />
                        <button type="submit" class="btn btn-sm btn-danger w-100">Ara</button>
                    </div>

                </div>

            </form>
        </div>
       
    </div>
    <div id="carouselExampleFade" class="carousel slide carousel-fade my-3" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="/images/navbar-image-deeme.jpg" class="d-block w-100" height="700" alt="...">
            </div>
            <div class="carousel-item">
                <img src="/images/slider2.png" class="d-block w-100" height="700" alt="...">
            </div>
            <div class="carousel-item">
                <img src="/images/slider4.png" class="d-block w-100" height="700" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>